language: python
arch:
 - amd64
 - ppc64le

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# test command
script: python setup.py install && python CommonMark/test/test-CommonMark.py -np && cmark.py README.md && cmark.py README.md -a && cmark.py README.md -aj
